### ISSUE TITLE
[Bug]: The console output pane has a `charset` of US-ASCII rather than UTF-8

### ISSUE THREAD

**Issue by Basil-Dot-Work** [java/devrel#15] opened 2023-10-18 20:06 UTC
### What happened?

The title says it all: The default character encoding of the Dev.Java Playground’s console pane is US-ASCII. For maximum compatibility, it should be UTF-8.

Run:  

`System.out.println( System.out.charset() ) ;`

>US-ASCII

So of course characters in Unicode beyond ASCII are garbled.

Run:

`System.out.println( "Kıvanç Aydoğan" ) ;`

>K?van? Aydo?an

Solution: Default the `charset` of the console pane to UTF-8.

### OS

macOS

### What browsers are you seeing the problem on?

Safari

### Contact Details (optional)

BasilDotWork@gmail.com

### Additional information

Leave blank

**Comment by denismakogon** [comment] 2023-10-18 20:20
Thank you for reporting this, we highly appreciate your attention to Java Playground. We are aware of this problem and right now in a process of testing a fix for this problem. There's a plan to release an update shortly. We will update this ticket as soon as the issue resolved.

**Comment by delabassee** [comment] 2023-10-19 12:54
Duplicate of #4

**Comment by delabassee** [comment] 2023-10-23 15:14
Solved.
<img width="586" alt="Screenshot 2023-10-23 at 17 14 15 (2)" src="https://github.com/java/devrel/assets/1822374/432abc84-e881-4479-9ba9-38b60822dbf4">

**Closed as completed by delabassee** 2023-10-23 15:14 UTC
Labels: playground
